### ISSUE TITLE
`to have calls satisfying` bug with sinon v7.2.4

### ISSUE THREAD

**Issue by joelmukuthu** [unexpectedjs/unexpected-sinon#92]
Hi,

I have [this failing build](https://travis-ci.org/knorm/knorm/builds/494948939#L1604-L1612) with sinon v7.2.4 (it was passing with v7.2.3):

```
TypeError: Cannot read property 'length' of undefined
      at /home/travis/build/knorm/knorm/node_modules/unexpected-sinon/lib/unexpected-sinon.js:155:39
      at Array.forEach (<anonymous>)
      at recordSpyCalls (node_modules/unexpected-sinon/lib/unexpected-sinon.js:153:11)
      at Object.handler (node_modules/unexpected-sinon/lib/unexpected-sinon.js:658:38)
      at executeExpect (node_modules/unexpected/build/lib/Unexpected.js:1300:65)
      at Unexpected.expect (node_modules/unexpected/build/lib/Unexpected.js:1304:18)
      at expect (node_modules/unexpected/build/lib/Unexpected.js:929:23)
      at Context.<anonymous> (test/Field.spec.js:118:9)
```

> PR for that build [here](https://github.com/knorm/knorm/pull/221) 

The [test](https://github.com/knorm/knorm/blob/0f351f922863331b7cda2914d16e5f42160f5035/test/Field.spec.js#L107-L124):

```js
describe('without a column name configured', function() {
  it("calls getColumnName to set the field's column name", function() {
    class Foo extends Model {}
    const stub = sinon
      .stub(Field.prototype, 'getColumnName')
      .returns('the column name');
    const field = new Field({
      name: 'bar',
      model: Foo,
      type: 'string'
    });
    expect(stub, 'to have calls satisfying', () => {
      stub('bar');
    });
    expect(field.column, 'to be', 'the column name');
    stub.restore();
  });
});
```

I'm not sure but it looks like these changes might be causing the issue https://github.com/sinonjs/sinon/pull/1975.

Let me know if I should provide any more info.

**Comment by papandreou** [comment]
Thanks! Fixed in 10.11.1.

You were right that it was due to the enumerability change.
